name: pytorch-env
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - scikit-learn
  - pillow
  - pytorch
  - torchvision
  - pip

  - pip:
      - torchsummary
